# Generated by Django 4.2.1 on 2024-12-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('mid', 'Mid'), ('low', 'Low')], default='mid', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('in_progress', 'IN PROGRESS'), ('completed', 'COMPLETED')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
